import type { APIRoute } from "astro";

export const GET: APIRoute = async ({ request }) => {
  // The sitemap is auto-generated by @astrojs/sitemap
  // This endpoint returns the generated sitemap
  const url = new URL(request.url);
  const sitemapUrl = new URL("/sitemap-0.xml", url.origin);

  return new Response(null, {
    status: 302,
    headers: {
      Location: sitemapUrl.toString(),
    },
  });
};
